version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies (if any)"
      - mvn -vv
  build:
    commands:
      - echo "Building Spring Boot JAR"
      - mvn clean package -DskipTests
      - echo "Renaming jar to app.jar"
      - cp target/*.jar app.jar
      - ls -la

artifacts:
  files:
    - app.jar
    - Procfile